---
language: ruby
sudo: required
services:
  - postgresql
  - docker
env:
  - RACK_ENV=test DATABASE_URL=postgresql://postgres@localhost/good4poc_test DOCKER_COMPOSE_VERSION=1.4.2
before_script:
  - docker-compose build
  - docker-compose up -d
install:
  - docker-compose run --entrypoint sh api bundle install --verbose --no-deployment --with development test
script:
  - docker-compose run api rake test
deploy:
  - provider: script
    script: scripts/deploy prod
    on:
      branch: master
  - provider: script
    script: scripts/deploy staging
    on:
      branch: develop
addons:
  ssh_known_hosts:
    - dokku.goodforpocin.tech
    - github.com
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d9bba348105e7154a7b6
    on_success: always
    on_failure: always
    on_start: always
