---
language: ruby
services:
  - postgresql
env:
  - RACK_ENV=test DATABASE_URL=postgresql://postgres@localhost/good4poc_test
before_script:
  - bundle config --delete without
  - cd mock-api && npm install && npm run serve
  - psql -c 'create database good4poc_test;' -U postgres
install:
  - bundle install --verbose --no-deployment --with development test
script:
  - bundle exec rake test
deploy:
  - provider: script
    script: scripts/deploy prod
    on:
      branch: master
  - provider: script
    script: scripts/deploy staging
    on:
      branch: develop
addons:
  ssh_known_hosts:
    - dokku.goodforpocin.tech
    - github.com
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d9bba348105e7154a7b6
    on_success: always
    on_failure: always
    on_start: always
