---
language: ruby
services:
  - postgresql

env:
  global:
    - RACK_ENV: test
    - DATABASE_URL: postgresql://postgres@localhost/good4poc_test

deploy:
  - provider: script
    script: scripts/deploy prod
    on:
      branch: master
      condition: $TRAVIS_PULL_REQUEST = false
  - provider: script
    script: scripts/deploy staging
    on:
      branch: develop
      condition: $TRAVIS_PULL_REQUEST = false

addons:
  ssh_known_hosts:
    - dokku.goodforpocin.tech
    - github.com

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d9bba348105e7154a7b6
    on_success: always
    on_failure: always
    on_start: always

before_script:
  - cd mock-api && npm install graphql && npm install && npm run build && npm run serve
  - psql -c 'create database good4poc_test;' -U postgres

script:
  - bundle install --with development test
  - bundle exec rake test
