#!/usr/bin/env bash

openssl aes-256-cbc -K $encrypted_5615895e9f52_key -iv $encrypted_5615895e9f52_iv -in ./.travis/deploy_key.enc -out ./.travis/deploy_key -d
eval "$(ssh-agent -s)"
chmod 600 .travis/deploy_key
ssh-add .travis/deploy_key

# Get the latest changes.
git fetch origin

git remote add dokku-prod dokku@dokku.goodforpocin.tech:api-prod
git remote add dokku-staging dokku@dokku.goodforpocin.tech:api-staging

git push "dokku-$1" "${TRAVIS_COMMIT}:master"
